import React from 'react'
import { FaBehance, FaFacebook, FaLinkedin, FaTwitter } from 'react-icons/fa'
export const links = [
  {
    id: 1,
    url: '/',
    text: 'latest news',
  },
  {
    id: 2,
    url: '/categories',
    text: 'search',
  },
]

export const social = [
  {
    id: 1,
    url: 'https://www.twitter.com',
    icon: <FaFacebook />,
  },
  {
    id: 2,
    url: 'https://www.twitter.com',
    icon: <FaTwitter />,
  },
  {
    id: 3,
    url: 'https://www.twitter.com',
    icon: <FaLinkedin />,
  },
  {
    id: 4,
    url: 'https://www.twitter.com',
    icon: <FaBehance />,
  },
]

export const categories = [
  [
    'regional',
    'technology',
    'lifestyle',
    'business',
    'general',
    'programming',
    'science',
    'entertainment',
    'world',
    'sports',
    'finance',
    'academia',
  ],
  [
    'politics',
    'health',
    'opinion',
    'food',
    'game',
    'fashion',
    'academic',
    'crap',
    'travel',
    'culture',
    'economy',
    'environment',
  ],
  [
    'art',
    'music',
    'notsure',
    'CS',
    'education',
    'redundant',
    'television',
    'commodity',
    'movie',
    'entrepreneur',
    'review',
    'auto',
  ],
  [
    'energy',
    'celebrity',
    'medical',
    'gadgets',
    'design',
    'EE',
    'security',
    'mobile',
    'estate',
    'funny',
  ],
]

export const regions = [
  {
    'United State': 'US',
    Taiwan: 'TW',
    German: 'DE',
    'United Kingdom': 'GB',
    China: 'CN',
    India: 'IN',
    Spain: 'ES',
    Italy: 'IT',
    Poland: 'PL',
    Australia: 'AU',
    Malaysia: 'MY',
    Singapore: 'SG',
    Canada: 'CA',
    'South Korea': 'KR',
    Denmark: 'DK',
    France: 'FR',
  },
  {
    Belgium: 'BE',
    Japan: 'JP',
    Austria: 'AT',
    Portugal: 'PT',
    Philippines: 'PH',
    'Hong Kong': 'HK',
    Argentina: 'AR',
    Venezuela: 'VE',
    Brazil: 'BR',
    Finland: 'FI',
    Indonedia: 'ID',
    Vietnam: 'VN',
    Mexico: 'MX',
    Greece: 'GR',
    Netherlands: 'NL',
    Norway: 'NO',
  },
  {
    'New Zealand': 'NZ',
    Russia: 'RU',
    'Saudi-Arabia': 'SA',
    Switzerland: 'CH',
    Thailand: 'TH',
    'United Arab Emirates': 'AE',
    Ireland: 'IE',
    Iran: 'IR',
    Iraq: 'IQ',
    Romania: 'RO',
    Afghanistan: 'AF',
    Zimbabwe: 'ZW',
    Myanmar: 'MM',
    Sweden: 'SE',
    Peru: 'PE',
    Panama: 'PA',
  },
  {
    Egypt: 'EG',
    Turkey: 'TR',
    Israel: 'IL',
    'Czech Republic': 'CZ',
    Bangladesh: 'BD',
    Nigeria: 'NG',
    Kenya: 'KE',
    Chile: 'CL',
    Uruguay: 'UY',
    Ecuador: 'EC',
    Serbia: 'RS',
    Hungary: 'HU',
    Slovenia: 'SI',
    Gahana: 'GH',
    Bolivia: 'BO',
    Pakistan: 'PK',
  },
  {
    Colombia: 'CO',
    'North Korea': 'NK',
    Paraguay: 'PY',
    Palestine: 'PS',
    Estonia: 'EE',
    Lebanon: 'LB',
    Qatar: 'QA',
    Kuwait: 'KW',
    Cambodia: 'KH',
    Nepal: 'NP',
    Luxembourg: 'LU',
    Bosnia: 'BA',
    Europe: 'EU',
    Asia: 'ASIA',
    International: 'INT',
  },
]

export const languages = [
  {
    Arabic: 'ar',
    Chinese: 'zh',
    Dutch: 'nl',
    English: 'en',
    Finnish: 'fi',
    French: 'fr',
    German: 'de',
    Hindi: 'hi',
  },

  {
    Italian: 'it',
    Japanese: 'ja',
    Korean: 'ko',
    Malay: 'msa',
    Portuguese: 'pt',
    Russian: 'ru',
    Spanish: 'es',
    Vietnamise: 'vi',
  },
]
